//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("THResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 拒絕存取.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非網站管理員無權取存這項資源.
        /// </summary>
        public static string AccessDeniedDescription {
            get {
                return ResourceManager.GetString("AccessDeniedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳號.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帳號資訊.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 以下各項為必填.
        /// </summary>
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版權所有.
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四月.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 八月.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驗證碼.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上圖的驗證碼.
        /// </summary>
        public static string CaptchaAbove {
            get {
                return ResourceManager.GetString("CaptchaAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 驗證碼錯誤.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 當代英語搭配辭典.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 換另一張圖.
        /// </summary>
        public static string ChangeCaptcha {
            get {
                return ResourceManager.GetString("ChangeCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更密碼.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更密碼成功.
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請檢查您的電郵以進行確認.
        /// </summary>
        public static string CheckConfirmEmail {
            get {
                return ResourceManager.GetString("CheckConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇語言.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉帖子.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 關閉.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你確定要關閉這帖子？.
        /// </summary>
        public static string CloseConfirmText {
            get {
                return ResourceManager.GetString("CloseConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搭配.
        /// </summary>
        public static string Collocate {
            get {
                return ResourceManager.GetString("Collocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搭配詞類.
        /// </summary>
        public static string CollocatingPOS {
            get {
                return ResourceManager.GetString("CollocatingPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搭配型態.
        /// </summary>
        public static string CollocationPattern {
            get {
                return ResourceManager.GetString("CollocationPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入搭配型態.
        /// </summary>
        public static string CollocationPatternRequired {
            get {
                return ResourceManager.GetString("CollocationPatternRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搭配詞類.
        /// </summary>
        public static string ColPos {
            get {
                return ResourceManager.GetString("ColPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇搭配詞類.
        /// </summary>
        public static string ColPosRequired {
            get {
                return ResourceManager.GetString("ColPosRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搭配單字.
        /// </summary>
        public static string ColWord {
            get {
                return ResourceManager.GetString("ColWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        public static string CommandButtonText {
            get {
                return ResourceManager.GetString("CommandButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認帳號.
        /// </summary>
        public static string ConfirmAccount {
            get {
                return ResourceManager.GetString("ConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請點擊這連結以確認新帳戶.
        /// </summary>
        public static string ConfirmAccountByLink {
            get {
                return ResourceManager.GetString("ConfirmAccountByLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您確定要刪除這個項目嗎？.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認新密碼.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 請確認新密碼.
        /// </summary>
        public static string ConfirmNewPasswordError {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認密碼.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認密碼錯誤，請再次確認密碼。.
        /// </summary>
        public static string ConfirmPasswordError {
            get {
                return ResourceManager.GetString("ConfirmPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請確認密碼.
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認您的新帳戶.
        /// </summary>
        public static string ConfirmYourAccount {
            get {
                return ResourceManager.GetString("ConfirmYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連結.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聯絡站長.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言已送出.
        /// </summary>
        public static string ContactCompleted {
            get {
                return ResourceManager.GetString("ContactCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 謝謝您寶貴的意見。.
        /// </summary>
        public static string ContactCompletedParagraph {
            get {
                return ResourceManager.GetString("ContactCompletedParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若您對本站有任何疑問或建議，歡迎與站長聯絡。.
        /// </summary>
        public static string ContactParagraph {
            get {
                return ResourceManager.GetString("ContactParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果你想更多的細節，請與網站管理員&lt;a href=&apos;contact.aspx&apos;&gt;聯繫&lt;/a&gt;報告此問題。.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情景片語.
        /// </summary>
        public static string ContextualPhrase {
            get {
                return ResourceManager.GetString("ContextualPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繼續搜尋.
        /// </summary>
        public static string ContinueToSearch {
            get {
                return ResourceManager.GetString("ContinueToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版權所有不得轉載.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊新帳號.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建立個人檔案.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 舊密碼.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 請輸入舊密碼.
        /// </summary>
        public static string CurrentPasswordError {
            get {
                return ResourceManager.GetString("CurrentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 舊密碼錯誤，請再次輸入舊密碼。.
        /// </summary>
        public static string CurrentPasswordNotMatch {
            get {
                return ResourceManager.GetString("CurrentPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料庫連線失敗.
        /// </summary>
        public static string DbConnectionFailed {
            get {
                return ResourceManager.GetString("DbConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出了問題的資料庫引擎.
        /// </summary>
        public static string DBEnginesInTrouble {
            get {
                return ResourceManager.GetString("DBEnginesInTrouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新用戶您好.
        /// </summary>
        public static string DearNewUser {
            get {
                return ResourceManager.GetString("DearNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十二月.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 定義.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除帖子.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除帖子.
        /// </summary>
        public static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你確定要刪除這帖子？.
        /// </summary>
        public static string DeleteConfirmText {
            get {
                return ResourceManager.GetString("DeleteConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這電郵帳戶已有人使用，請輸入另一個電郵帳戶。.
        /// </summary>
        public static string DuplicatedEmail {
            get {
                return ResourceManager.GetString("DuplicatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重覆輸入項目.
        /// </summary>
        public static string DuplicatedEntry {
            get {
                return ResourceManager.GetString("DuplicatedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這名稱已有人使用，請輸入另一個名稱。.
        /// </summary>
        public static string DuplicatedUserName {
            get {
                return ResourceManager.GetString("DuplicatedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修改個人資料.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電郵.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入正確電郵格式.
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電郵尚未確認.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電郵尚未確認.
        /// </summary>
        public static string EmailNotConfirmedHeading {
            get {
                return ResourceManager.GetString("EmailNotConfirmedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對不起，您的電郵尚未確認，無法登錄。.
        /// </summary>
        public static string EmailNotConfirmedParagraph {
            get {
                return ResourceManager.GetString("EmailNotConfirmedParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入電郵.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這電郵已經註冊.
        /// </summary>
        public static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入上圖的驗證碼.
        /// </summary>
        public static string EnterCaptchaAbove {
            get {
                return ResourceManager.GetString("EnterCaptchaAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入以下的驗證碼.
        /// </summary>
        public static string EnterCaptchaBelow {
            get {
                return ResourceManager.GetString("EnterCaptchaBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入關鍵字.
        /// </summary>
        public static string EnterKeyword {
            get {
                return ResourceManager.GetString("EnterKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入名稱及密碼.
        /// </summary>
        public static string EnterUsernamePassword {
            get {
                return ResourceManager.GetString("EnterUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入日文條目.
        /// </summary>
        public static string EntryJapRequired {
            get {
                return ResourceManager.GetString("EntryJapRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入簡中條目.
        /// </summary>
        public static string EntryZhsRequired {
            get {
                return ResourceManager.GetString("EntryZhsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入繁中條目.
        /// </summary>
        public static string EntryZhtRequired {
            get {
                return ResourceManager.GetString("EntryZhtRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在發送郵件時出錯。.
        /// </summary>
        public static string ErrorInSendingMail {
            get {
                return ResourceManager.GetString("ErrorInSendingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例句.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例句(中文).
        /// </summary>
        public static string ExampleChi {
            get {
                return ResourceManager.GetString("ExampleChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例句來源一覧：.
        /// </summary>
        public static string ExampleSourceText {
            get {
                return ResourceManager.GetString("ExampleSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例句：.
        /// </summary>
        public static string ExampleText {
            get {
                return ResourceManager.GetString("ExampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 二月.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 忘記密碼.
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 討論區.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該方法正在撰寫中，謝謝。.
        /// </summary>
        public static string FunctionBeingImplemented {
            get {
                return ResourceManager.GetString("FunctionBeingImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 午安.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 晚安.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 早安.
        /// </summary>
        public static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您好，以下是您的密碼，請小心儲存，謝謝!!.
        /// </summary>
        public static string HereIsYourPassword {
            get {
                return ResourceManager.GetString("HereIsYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 希望您滿意本站所提供的服務!.
        /// </summary>
        public static string HopeEnjoyOurService {
            get {
                return ResourceManager.GetString("HopeEnjoyOurService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果沒有帳號，請前往.
        /// </summary>
        public static string IfNoAccount {
            get {
                return ResourceManager.GetString("IfNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collocate.jpg.
        /// </summary>
        public static string ImgCollocate {
            get {
                return ResourceManager.GetString("ImgCollocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登錄失敗.
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一月.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七月.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 六月.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三月.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼最多不能超過20個字元.
        /// </summary>
        public static string MaxPasswordLengthError {
            get {
                return ResourceManager.GetString("MaxPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 五月.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 留言.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入留言.
        /// </summary>
        public static string MessageRequired {
            get {
                return ResourceManager.GetString("MessageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼最少要有6個字元.
        /// </summary>
        public static string MinPasswordLengthError {
            get {
                return ResourceManager.GetString("MinPasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required!.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要註解.
        /// </summary>
        public static string NeedRemark {
            get {
                return ResourceManager.GetString("NeedRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密碼.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 確認新密碼，請再次確認新密碼。.
        /// </summary>
        public static string NewPasswordCompareError {
            get {
                return ResourceManager.GetString("NewPasswordCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * 請輸入新密碼.
        /// </summary>
        public static string NewPasswordError {
            get {
                return ResourceManager.GetString("NewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一頁.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒有存取權限.
        /// </summary>
        public static string NoAccessRights {
            get {
                return ResourceManager.GetString("NoAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沒有可用數據.
        /// </summary>
        public static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對不起，目前詞庫沒有您要找的搭配資料。.
        /// </summary>
        public static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對不起，目前沒有 &lt;span class=&apos;word&apos;&gt;{0}&lt;/span&gt; 的搭配資料。 .
        /// </summary>
        public static string NoSearchResult_WordOnly {
            get {
                return ResourceManager.GetString("NoSearchResult_WordOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對不起，目前沒有搭配 &lt;span class=&apos;word&apos;&gt;{0}&lt;/span&gt; 的 &lt;span class=&apos;colword&apos;&gt;{1}&lt;/span&gt; 資料。.
        /// </summary>
        public static string NoSearchResult_WordPOS {
            get {
                return ResourceManager.GetString("NoSearchResult_WordPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名詞.
        /// </summary>
        public static string noun {
            get {
                return ResourceManager.GetString("noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 該使用者不存在.
        /// </summary>
        public static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十一月.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 十月.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 其他.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 牛津英語搭配詞典.
        /// </summary>
        public static string Oxford {
            get {
                return ResourceManager.GetString("Oxford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所請求的頁面或資源沒有被發現。.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首頁.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼必須是 6 個至 20 個任何字元.
        /// </summary>
        public static string PasswordFormat {
            get {
                return ResourceManager.GetString("PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼字數必須在 6 至 20 個之內.
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取回密碼.
        /// </summary>
        public static string PasswordRecovery {
            get {
                return ResourceManager.GetString("PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密碼已寄出，請妥善保存。.
        /// </summary>
        public static string PasswordRecoverySuccessText {
            get {
                return ResourceManager.GetString("PasswordRecoverySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入密碼.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Select -.
        /// </summary>
        public static string PatternDropDownListSelect {
            get {
                return ResourceManager.GetString("PatternDropDownListSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請進行登錄.
        /// </summary>
        public static string PleaseLogIn {
            get {
                return ResourceManager.GetString("PleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇國家.
        /// </summary>
        public static string PleaseSelectCountry {
            get {
                return ResourceManager.GetString("PleaseSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 詞類.
        /// </summary>
        public static string Pos {
            get {
                return ResourceManager.GetString("Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發帖.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一頁.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料讀取中，請稍候....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資料讀取中.
        /// </summary>
        public static string ProgressTitle {
            get {
                return ResourceManager.GetString("ProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敬上.
        /// </summary>
        public static string Regards {
            get {
                return ResourceManager.GetString("Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊新帳號.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊確認電郵已寄出至您的電郵帳戶。.
        /// </summary>
        public static string RegisterConfirmEmailSent {
            get {
                return ResourceManager.GetString("RegisterConfirmEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註冊成功.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 註解.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保持登入狀態.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補發確認電郵連結.
        /// </summary>
        public static string RequestAnotherConfirmEmailLink {
            get {
                return ResourceManager.GetString("RequestAnotherConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請求超時。這可能是由於過高的流量。請稍後再試一次。.
        /// </summary>
        public static string RequestTimeOut {
            get {
                return ResourceManager.GetString("RequestTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到資源.
        /// </summary>
        public static string ResourcesNotFound {
            get {
                return ResourceManager.GetString("ResourcesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伺服器無法為您提供這項資源.
        /// </summary>
        public static string ResourcesNotFoundDescription {
            get {
                return ResourceManager.GetString("ResourcesNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 身份.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇搭配該單字的詞類：.
        /// </summary>
        public static string SearchColPosText {
            get {
                return ResourceManager.GetString("SearchColPosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入搭配上方單字的單字：.
        /// </summary>
        public static string SearchColWordText {
            get {
                return ResourceManager.GetString("SearchColWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋結果.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入被搭配的單字：.
        /// </summary>
        public static string SearchWordText {
            get {
                return ResourceManager.GetString("SearchWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看詳細定義.
        /// </summary>
        public static string SeeDefinition {
            get {
                return ResourceManager.GetString("SeeDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送出.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 九月.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服務器遇到了意外情況，防止它履行的要求。請稍後再試一次。.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享至Facebook.
        /// </summary>
        public static string Share_Facebook {
            get {
                return ResourceManager.GetString("Share_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享至Google+.
        /// </summary>
        public static string Share_Google {
            get {
                return ResourceManager.GetString("Share_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享至LinkedIn.
        /// </summary>
        public static string Share_LinkedIn {
            get {
                return ResourceManager.GetString("Share_LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享至Twitter.
        /// </summary>
        public static string Share_Twitter {
            get {
                return ResourceManager.GetString("Share_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 站內搜尋.
        /// </summary>
        public static string SiteSearch {
            get {
                return ResourceManager.GetString("SiteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用詞搭配.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 對不起.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 來源.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 來源：.
        /// </summary>
        public static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統異常.
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系統將會於.
        /// </summary>
        public static string SystemWillRedirectText1 {
            get {
                return ResourceManager.GetString("SystemWillRedirectText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒後自動導回首頁.
        /// </summary>
        public static string SystemWillRedirectText2 {
            get {
                return ResourceManager.GetString("SystemWillRedirectText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感謝確認。您現在可以進行登錄。.
        /// </summary>
        public static string ThanksForConfirmAccount {
            get {
                return ResourceManager.GetString("ThanksForConfirmAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 感謝註冊本站。稍後系統會導向回首頁。.
        /// </summary>
        public static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這頁在建構中，請稍後再來訪。.
        /// </summary>
        public static string ThisPageUnderConstruction {
            get {
                return ResourceManager.GetString("ThisPageUnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網頁錯誤.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string ToLogin {
            get {
                return ResourceManager.GetString("ToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網站維修中，不日復工，謝謝。.
        /// </summary>
        public static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的錯誤。.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 發生不明錯誤.
        /// </summary>
        public static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網址錯誤.
        /// </summary>
        public static string UrlErrors {
            get {
                return ResourceManager.GetString("UrlErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請檢查網址是否輸入錯誤.
        /// </summary>
        public static string UrlErrorsDescription {
            get {
                return ResourceManager.GetString("UrlErrorsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用其他帳號登入。.
        /// </summary>
        public static string UseOtherServicesLogin {
            get {
                return ResourceManager.GetString("UseOtherServicesLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用戶.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用戶名稱.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用戶名稱或電郵.
        /// </summary>
        public static string UserNameEmailForLogin {
            get {
                return ResourceManager.GetString("UserNameEmailForLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名稱與電郵互不相符.
        /// </summary>
        public static string UserNameEmailNotMatch {
            get {
                return ResourceManager.GetString("UserNameEmailNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入用戶名稱或電郵.
        /// </summary>
        public static string UserNameEmailRequired {
            get {
                return ResourceManager.GetString("UserNameEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名稱與密碼互不相符.
        /// </summary>
        public static string UserNamePasswordNotMatch {
            get {
                return ResourceManager.GetString("UserNamePasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入用戶名稱.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 這用戶名稱已經註冊.
        /// </summary>
        public static string UserNameTaken {
            get {
                return ResourceManager.GetString("UserNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到用戶登錄資料.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用{0}帳號來登入.
        /// </summary>
        public static string UsingAccountToLogin {
            get {
                return ResourceManager.GetString("UsingAccountToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動詞.
        /// </summary>
        public static string verb {
            get {
                return ResourceManager.GetString("verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 網路.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ， 歡迎！.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單字.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用詞搭配.
        /// </summary>
        public static string WordCollocation {
            get {
                return ResourceManager.GetString("WordCollocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入被搭配單字.
        /// </summary>
        public static string WordRequired {
            get {
                return ResourceManager.GetString("WordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸入單字建議.
        /// </summary>
        public static string WordSuggestion {
            get {
                return ResourceManager.GetString("WordSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目前詞庫存有單字(名詞)如下.
        /// </summary>
        public static string WordSuggestionText {
            get {
                return ResourceManager.GetString("WordSuggestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
